### ISSUE TITLE
Adopt use of `meta.header`

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatModelUtils#117]
**Is your feature request related to a problem? Please describe.**
pysat is moving to use of `meta.header` rather than having general file attributes attached to Instrument object.

**Describe the solution you'd like**
Review instrument support code and adopt latest pysat standard.

**Describe alternatives you've considered**
Let things go out of date.

**Additional context**

**Comment by jklenzing** [comment]
All models load using the standard `utils.io.load_netcdf` function, so this should be fine.
